title: kawa1lg1rl's blog
description: 
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Nyan: https://youtu.be/2yJgwwDcgV8

color_scheme: dark
ga_tracking: G-W7F1JV8VX6
ga_tracking_anonymize_ip: true 